[package]
name = "libabsho"
version = "1.0.8"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
runtime = { path = "../runtime", features = ["core", "checkout"] }
tokio = { version = "1", features = ["full"] }
