[package]
name = "savevoucher"
version = "1.2.5"
edition = "2021"
authors = ["Paijo"]
description = "Save Voucher"
build = "build.rs"

[build-dependencies]
thunk = { git = "https://github.com/cari-404/thunk.git", package = "thunk-rs" }
winresource = "0.1"

[package.metadata.winresource]
FileDescription = "Save Voucher"
LegalCopyright = "By Paijo"
OriginalFilename = "claimshopee.exe"
CompanyName = "Paijo"

[dependencies]
runtime = { path = "../runtime" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
chrono = "0.4"
structopt = "0.3"
num_cpus = "1.16"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_System_Console"] }