[package]
name = "draw"
version = "0.10.9"
edition = "2024"

[dependencies]
runtime = { path = "../runtime" }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
anyhow = "1.0"
rquest = { version = "1.5.5", features = ["gzip"] }
serde_json = "1"