[package]
name = "video"
version = "1.1.1"
edition = "2021"

[dependencies]
runtime = { path = "../runtime", features = ["core"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
anyhow = "1.0"
structopt = "0.3"
rquest = { version = "1.5.5", features = ["gzip"] }
serde_json = "1"